<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BricksCms\Module'                     => __DIR__ . '/Module.php',
    'BricksCms\Controller\IndexController' => __DIR__ . '/src/BricksCms/Controller/IndexController.php',
    'BricksCms\Plugin\Test'                => __DIR__ . '/src/BricksCms/Plugin/Test.php',
);
