<div class="container bricks-index-index">
	<div class="row">
		<div class="col-md-9">
			<div class="box">
				<h1><div class="pad-5">Welcome to BrIcKs</div></h1>
				<div class="pad-10">
					<img src="<?php echo $this->Resource('BricksCms/img/logo.png'); ?>" alt="BrIcKs" class="left left-pad-10" />
					<p>
						Are you interested in building a community around Bricks?
						<br />
						You are welcome in the community - <a href="http://www.bricks-cms.org/">Bricks CMS Webpage</a>. 
					</p>
				</div>
			</div>
			<div class="row row-full-height">
				<div class="col-md-4 col-md-fit-height">
					<div class="box">
						<h1><div class="pad-5">Status der Entwicklung</div></h1>
						<div class="pad-10">
							Ich hab das Menu schön.
						</div>
					</div>	
				</div>
				<div class="col-md-8 col-md-fit-height">
					<div class="box">
						<h1><div class="pad-5">Status der Entwicklung</div></h1>
						<div class="pad-10">
							Ich hab das Menu schön.
						</div>
					</div>	
				</div>
			</div>
		</div>
		<div class="col-md-3">
			<div class="box pad-10">
				<ul class="list-group">
					<li class="list-group-item"><a href="http://www.bricks-cms.org/">Bricks CMS Webpage</a></li>
					<li class="list-group-item"><a href="http://www.bricks-cms.org/forum">Bricks CMS Forum</a></li>
					<li class="list-group-item"><a href="http://www.bricks-cms.org/wiki">Bricks Wiki</a></li>
				</ul>
			</div>
			<div class="box pad-10">				
				Working on a basic layout (css) setup.
			</div>			
		</div>
	</div>	
</div>