<section role="main">
	<section role="article">
		<article>
			<header>
				<h1>Welcome to BrIcKs</h1>
			</header>
			<content>
				<img src="<?php echo $this->Resource('BricksCms/img/logo.png'); ?>" alt="BrIcKs" />
				<p>
					Are you interested in building a community around Bricks?
					<br />
					You are welcome in the community - <a href="http://www.bricks-cms.org/">Bricks CMS Webpage</a>. 
				</p>
			</content>
		</article>
		<article>
			<header>
				<h1>Status der Entwicklung</h1>
			</header>
			<content>
				<p>
					First Line.<br />
					Second Line to test height will fit.
				</p>
			</content>
		</article>
		<article>
			<header>
				<h1>Status der Entwicklung</h1>
			</header>
			<content>
				<p>OneLine</p>
			</content>
		</article>
		<article>
			<header>
				<h1>Status der Entwicklung</h1>
			</header>
			<content>
				<p>
					First Line.<br />
					Second Line to test height will fit.
				</p>
			</content>
		</article>
		<article>
			<header>
				<h1>Status der Entwicklung</h1>
			</header>
			<content>
				<p>OneLine</p>
			</content>
		</article>
	</section>
	<aside>
		<article>
			<content>
				<ul>
					<li><a href="http://www.bricks-cms.org/">Bricks CMS Webpage</a></li>
					<li><a href="http://www.bricks-cms.org/forum">Bricks CMS Forum</a></li>
					<li><a href="http://www.bricks-cms.org/wiki">Bricks Wiki</a></li>
				</ul>
			</content>
		</article>
		<article>
			<content>
				<p>Working on a basic layout (css) setup.</p>
			</content>
		</article>
	</aside>
</section>