<section role="main">
	<section role="article">
		<article>
			<header>
				<h1><?php echo $this->translate('Write public files'); ?></h1>
			</header>
			<content>
				<form name="publish" action="<?php echo $this->Url('bricks.asset.publish.do'); ?>" method="post">
					<?php echo $this->Form($this->publishForm); ?>
				</form>
			</content>
		</article>
	</section>
	<aside>
		<article>
			<content>
				<p>
					<?php echo $this->translate('Before you can use the public files of a module they have to be published in a public reachable directory.'); ?>				
				</p>
				<p>
					<?php echo $this->translate('To use the published resources you\'ve to begin with the modules name followed by the path as it is stored in your modules public dir.'); ?>
				</p>
				<pre><code>&lt;?php 
	$this-&gt;HeadLink()-&gt;appendStylesheet('MyModuleName/path/to/css.css');
?&gt;</code></pre>
			</content>
		</article>
	</aside>
</section>