<?php echo $this->doctype(); ?>
<html lang="de">
    <head>
        <meta charset="utf-8">     
        <base href="<?php echo $this->basePath('/'); ?>" />   
        <?php 
        	echo $this->headTitle('BrIcKs')->setSeparator(' - ')->setAutoEscape(false);
        	echo $this->headMeta()
            	->appendName('viewport', 'width=device-width, initial-scale=1.0')
            	->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
			echo $this->headScript();
			echo $this->headLink();			
        ?>
    </head>
    <body>
    
    	<header class="header">
    		<nav class="nav container">
    			<ul>
    				<li class="active"><a href="<?php echo $this->Url('bricks.index.index'); ?>">Home</a></li>
			        <li>
			        	<a href="<?php echo $this->Url('bricks.asset.publish'); ?>">Asset Service</a>
			        	<ul>
			        		<li><a href="#">Test</a></li>
			        		<li><a href="#">Längerer String</a></li>
			        		<li><a href="#">Längerer String Längerer String</a></li>
			        	</ul>
			        </li>
    			</ul>
    		</nav>    		
    	</header>
    
    	<content class="content"><?php echo $this->layout()->content; ?></content>
	    
	    <footer class="footer"></footer>
	    
    </body>    
</html>