<?php echo $this->doctype(); ?>
<html lang="de">
    <head>
        <meta charset="utf-8">     
        <base href="<?php echo $this->basePath('/'); ?>" />   
        <?php 
        	echo $this->headTitle('BrIcKs')->setSeparator(' - ')->setAutoEscape(false);
        	echo $this->headMeta()
            	->appendName('viewport', 'width=device-width, initial-scale=1.0')
            	->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
			echo $this->headScript();
			echo $this->headLink();			
        ?>
    </head>
    <body>
    
    	<header class="header">    		
    	</header>
    
    	<content>
    		<?php echo $this->layout()->content; ?>
    	</content>
	    
    </body>    
</html>